apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-pod
  name: web-pod
  namespace: web-app
spec:
  containers:
  - image: nginx
    name: web-pod
    envFrom:
    - configMapRef:
        name: web-config
    - secretRef:
        name: db-secret
